from pathlib import Path
import re
import sys


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

import plot_stddev_table_from_cumulativecsv as plot_logic
from utils.dataset_reference_metrics import (
    canonical_dataset_key,
    dataset_graph_size_text,
    dataset_homophily_text,
    dataset_li_text,
)


OUTPUT_DIR = SRC_ROOT / "outputs/latex_tables"
COMBINED_TABLE_FILENAME = "all_tablex.tex"
COMBINED_DATASET_ORDER = [
    "Cora",
    "CiteSeer",
    "PubMed",
    "Computers",
    "Photo",
    "chameleon",
    "squirrel",
    "wisconsin",
    "Texas",
    "Actor",
    "roman_empire",
]


def latex_escape(value):
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def latex_label(value):
    return re.sub(r"[^a-z0-9]+", "-", str(value).lower()).strip("-")


def table_filename(dataset_name):
    safe_name = str(dataset_name).replace("/", "_").replace(" ", "_")
    return OUTPUT_DIR / f"{safe_name}_table.tex"


def shortstack(text):
    lines = [latex_escape(line) for line in str(text).split("\n")]
    return r"\shortstack{" + r"\\".join(lines) + "}"


def cell_text(fold_std, bold=False):
    content = rf"${fold_std:.2f}$"
    if bold:
        return r"{\boldmath\bfseries " + content + "}"
    return content


def dataset_selection(stats):
    datasets = [plot_logic.display_dataset_name(dataset) for dataset in plot_logic.DATASETS_TO_PLOT]
    if not datasets:
        datasets = sorted(stats["DatasetDisplay"].unique(), key=plot_logic.dataset_sort_key)
    if not plot_logic.INCLUDE_SYN_CORA:
        datasets = [
            dataset for dataset in datasets
            if not canonical_dataset_key(dataset).startswith("syn-cora")
        ]
    return datasets


def build_table_rows(dataset_stats, methods):
    rows = []
    models = [
        model for model in plot_logic.MODEL_ORDER
        if model in set(dataset_stats["Model"])
    ]

    for model in models:
        model_stats = dataset_stats[dataset_stats["Model"] == model]
        best_std = model_stats["MeanFoldStd"].min()
        row = [latex_escape(model)]

        for method in methods:
            values = model_stats[model_stats["Method"] == method]
            if values.empty:
                row.append(r"\textemdash")
                continue

            fold_std = float(values.iloc[0]["MeanFoldStd"])
            row.append(
                cell_text(
                    fold_std=fold_std,
                    bold=abs(fold_std - best_std) < 1e-12,
                )
            )

        rows.append(row)
    return rows


def dataset_table_lines(dataset_name, stats, include_comments=True):
    dataset_stats = stats[stats["DatasetDisplay"] == dataset_name]
    if dataset_stats.empty:
        print(f"Skipping {dataset_name}: no matching rows.")
        return None

    methods = plot_logic.displayed_methods(dataset_stats)
    rows = build_table_rows(dataset_stats, methods)
    if not rows:
        print(f"Skipping {dataset_name}: no configured models found.")
        return None

    headers = ["Model", *[
        shortstack(plot_logic.METHOD_LABELS[method])
        for method in methods
    ]]
    caption = (
        f"{dataset_name}: aggregated test-accuracy dispersion. "
        "Each cell reports the standard deviation across fold test accuracies. "
        f"{dataset_homophily_text(dataset_name)}; "
        f"{dataset_graph_size_text(dataset_name)}; "
        f"{dataset_li_text(dataset_name)}."
    )

    column_spec = "l" + "c" * len(methods)
    lines = []
    if include_comments:
        lines.extend([
            "% Auto-generated by src/one_time_scripts/latex_table_from_cumulativecsv.py",
            "% Requires \\usepackage{booktabs}.",
        ])

    lines.extend([
        r"\begin{table}[htbp]",
        r"\centering",
        r"\small",
        rf"\caption{{{latex_escape(caption)}}}",
        rf"\label{{tab:stddev-{latex_label(dataset_name)}}}",
        rf"\begin{{tabular}}{{{column_spec}}}",
        r"\toprule",
        " & ".join(headers) + r" \\",
        r"\midrule",
    ])

    for row in rows:
        lines.append(" & ".join(row) + r" \\")

    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ])

    return lines


def write_dataset_table(dataset_name, stats):
    lines = dataset_table_lines(dataset_name, stats)
    if lines is None:
        return None

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_path = table_filename(dataset_name)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def write_combined_table(stats):
    combined_lines = [
        "% Auto-generated by src/one_time_scripts/latex_table_from_cumulativecsv.py",
        "% Requires \\usepackage{booktabs}.",
        "",
    ]
    included_datasets = []

    for dataset_name in COMBINED_DATASET_ORDER:
        lines = dataset_table_lines(dataset_name, stats, include_comments=False)
        if lines is None:
            continue

        combined_lines.extend(lines)
        included_datasets.append(dataset_name)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_path = OUTPUT_DIR / COMBINED_TABLE_FILENAME
    output_path.write_text("\n".join(combined_lines), encoding="utf-8")
    return output_path, included_datasets


def main():
    df = plot_logic.load_cumulative_results()
    stats = plot_logic.summarize_fold_dispersion(df)
    datasets = dataset_selection(stats)

    print(f"Loaded {len(df)} relevant rows from {plot_logic.CUMULATIVE_RESULTS_FILE}.")
    print(f"Writing LaTeX tables to {OUTPUT_DIR}.")

    written = []
    for dataset_name in datasets:
        output_path = write_dataset_table(dataset_name, stats)
        if output_path is not None:
            written.append(output_path)
            print(f"Wrote {output_path}")

    combined_path, combined_datasets = write_combined_table(stats)
    print(f"Wrote {combined_path}")
    print(f"Combined table order: {', '.join(combined_datasets)}")
    print(f"Done. Wrote {len(written)} dataset tables plus {COMBINED_TABLE_FILENAME}.")


if __name__ == "__main__":
    main()
