#init_seeds: [100,101,102,103,104,105,106,107,108,109]
init_seeds: [100,101]
#  ,110,111,112,113,114,115,116,117,118,119]

#fixed by our problem definition
hidden_layers: 2
hidden_units: 64
optimizer: "Adam"
lr: 0.01
weight_decay: 5e-4
max_epochs: 1000
num_folds: 5

early_stopping_patience: 100
num_workers: 4

stratification_types: ["wdes"] #["random", "label", "wdes"]
wdes_properties: ["Degree", "Neighborhood Heterogeneity", "PageRank", "Eigenvector Centrality", "Clustering Coefficient"]
wdes_n_gen: 50
wdes_n_pop: 100
wdes_cxpb: 0.5
wdes_mutpb: 0.2
wdes_tournament_size: 3
fold_stat_properties: ["Degree", "Neighborhood Heterogeneity", "PageRank", "Eigenvector Centrality", "Clustering Coefficient"]
log_fold_statistics: true

#fold_seeds: [0,1,2,3,4,5,6,7,8,9]
fold_seeds: [0,1,2,3,4]
#fold_seeds: [3,4,5,6,7,8,9]

#model_names: ["MLP", "GCN", "GAT", "SAGE","MixHop", "GPRGNN", "H2GCN"]
model_names: ["H2GCN", "GCN", "GAT", "SAGE", "GPRGNN", "MLP"]

datasets: [
    "Cora",
#    "CiteSeer",
#    "PubMed",
#    "Computers",
#    "Photo",
    "chameleon",
#    "squirrel",
#    "crocodile",
    "Actor",
    "Texas",
]


plot_fold_statistics: false
run_csv_filename: "logs/StratifiedSamplingBaseline.csv"
fold_stats_csv_filename: "logs/FoldStatistics.csv"
